# -*- coding: utf-8 -*-
"""preprocess_annotation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f4BeaAclXgmuG144NzqV9qidu3jnUXaU
"""

from google.colab import drive
drive.mount("/content/drive", force_remount=True)

import pandas as pd
import numpy as np
import os

img_path = "/content/drive/MyDrive/kaggle/pneumonia/images/"
annot_df = pd.read_csv("/content/drive/MyDrive/kaggle/pneumonia/annot.csv")
imgs = os.listdir(img_path)

imgs = imgs[:6000]

m = round(0.8 * len(imgs))
train_imgs = imgs[:m]
val_imgs = imgs[m:]

_annot_df = annot_df.loc[annot_df["x"].notna(),:]
train_annot_df = _annot_df.loc[(_annot_df["patientId"] + ".jpg").isin(train_imgs),:]
train = pd.DataFrame()
train["filename"] = train_annot_df["patientId"] + ".jpg"
train["width"] = 1024
train["height"] = 1024
train["class"] = np.where(train_annot_df["Target"] == 0, pd.NA, "pneumonia")
train["xmin"] = train_annot_df["x"]
train["ymin"] = train_annot_df["y"]
train["xman"] = train_annot_df["x"] + train_annot_df["width"]
train["ymax"] = train_annot_df["y"] + train_annot_df["height"]
ims = train["filename"].unique()
imgs_dict = dict(zip(ims, range(len(ims))))
train["image_id"] = train["filename"].map(imgs_dict)

print(train.shape)
train.sort_values(by="image_id").head()

val_annot_df = _annot_df.loc[(_annot_df["patientId"] + ".jpg").isin(val_imgs),:]
val = pd.DataFrame()
val["filename"] = val_annot_df["patientId"] + ".jpg"
val["width"] = 1024
val["height"] = 1024
val["class"] = np.where(val_annot_df["Target"] == 0, pd.NA, "pneumonia")
val["xmin"] = val_annot_df["x"]
val["ymin"] = val_annot_df["y"]
val["xmax"] = val_annot_df["x"] + val_annot_df["width"]
val["ymax"] = val_annot_df["y"] + val_annot_df["height"]
ims = val["filename"].unique()
imgs_dict = dict(zip(ims, range(len(ims))))
val["image_id"] = val["filename"].map(imgs_dict)

print(val.shape)
val.sort_values(by="image_id").head()

train.to_csv("/content/drive/MyDrive/kaggle/pneumonia/annotation_train.csv", header=True, index=False)
val.to_csv("/content/drive/MyDrive/kaggle/pneumonia/annotation_val.csv", header=True, index=False)